FROM golang:1.22-alpine AS build

WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN go build -o healthtech-backend main.go

FROM alpine:3.20
WORKDIR /app
COPY --from=build /app/healthtech-backend .
EXPOSE 8080
ENTRYPOINT ["./healthtech-backend"]
